# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :screenshots do
    capture_screenshots
    # frame_screenshots(white: false)
  end

  lane :development_profile do
    sync_code_signing(
      type: "development",
      app_identifier: "dev.eclectic.KFinder"
    )
  end

  lane :appstore_profile do
    sync_code_signing(
      type: "appstore",
      app_identifier: "dev.eclectic.KFinder"
    )
  end

  lane :profiles do
    development_profile
    appstore_profile
  end

  lane :build_release do
    appstore_profile
    build_app(
      clean: true,
      scheme: "KFinder"
    )
  end

  lane :beta do
    build_release
    upload_to_testflight
  end

end
