# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"]
    )
  end

  lane :screenshots do
    capture_screenshots
    # frame_screenshots(white: false)
  end

  lane :development_profile do
    sync_code_signing(
      type: "development",
      app_identifier: "dev.eclectic.KFinder"
    )
  end

  lane :appstore_profile do
    sync_code_signing(
      type: "appstore",
      app_identifier: "dev.eclectic.KFinder"
    )
  end

  lane :profiles do
    development_profile
    appstore_profile
  end

  lane :build_release do
    appstore_profile
    build_app(
      clean: true,
      scheme: "KFinder"
    )
  end

  lane :beta do
    increment_build_number
    build_release
    upload_to_testflight
    commit_version_bump(
      xcodeproj: "KFinder.xcodeproj",
      message: "build: auto-bump"
    )
  end

end
