name: "CI Build"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "08 8 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build
        run: set -o pipefail && xcodebuild clean build -scheme KFinder -project KFinder.xcodeproj -destination "platform=iOS Simulator,OS=26.2,name=iPhone 17 Air" | xcpretty && exit ${PIPESTATUS[0]}
